# Generated by Django 5.0.1 on 2024-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary', models.CharField(max_length=255, verbose_name='Город-зарплата')),
                ('salary_by_city', models.IntegerField(verbose_name='Уровень зарплат по городам')),
                ('city_percentage', models.CharField(max_length=255, verbose_name='Город-доля вакансий')),
                ('percentage_by_city', models.FloatField(verbose_name='Доля вакансий по городам')),
                ('charts_city', models.ImageField(blank=True, upload_to='charts', verbose_name='График стат-ки по годам')),
            ],
            options={
                'verbose_name': 'Статистика по городам',
                'verbose_name_plural': 'Статистика по городам',
            },
        ),
        migrations.CreateModel(
            name='SkillsStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_skills', models.CharField(max_length=255, verbose_name='Год')),
                ('key_skills', models.TextField(verbose_name='Топ-20 навыков по годам')),
                ('skills_count', models.TextField(verbose_name='Частотность навыков')),
                ('charts_skills', models.ImageField(blank=True, upload_to='charts', verbose_name='Графики стат-ки по навыкам')),
            ],
            options={
                'verbose_name': 'ТОП-20 навыков по годам',
                'verbose_name_plural': 'ТОП-20 навыков по годам',
            },
        ),
        migrations.CreateModel(
            name='YearStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('salary_by_years', models.IntegerField(verbose_name='Динамика зарплат')),
                ('salary_by_years_profession', models.IntegerField(verbose_name='Динамика зарплат для профессии')),
                ('number_vac_by_years', models.IntegerField(verbose_name='Динамика кол-ва вакансий')),
                ('number_profession_by_years', models.IntegerField(verbose_name='Динамика кол-ва вакансий для профессии')),
                ('charts_years', models.ImageField(blank=True, upload_to='charts', verbose_name='График стат-ки по годам')),
            ],
            options={
                'verbose_name': 'Статистика по годам',
                'verbose_name_plural': 'Статистика по годам',
            },
        ),
    ]
